// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdb

import (
	"context"
	"database/sql"
	"man/db"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CountRoom provides a mock function for the type MockStore
func (_mock *MockStore) CountRoom(ctx context.Context, isActive sql.NullBool) (int64, error) {
	ret := _mock.Called(ctx, isActive)

	if len(ret) == 0 {
		panic("no return value specified for CountRoom")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sql.NullBool) (int64, error)); ok {
		return returnFunc(ctx, isActive)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sql.NullBool) int64); ok {
		r0 = returnFunc(ctx, isActive)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sql.NullBool) error); ok {
		r1 = returnFunc(ctx, isActive)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRoom'
type MockStore_CountRoom_Call struct {
	*mock.Call
}

// CountRoom is a helper method to define mock.On call
//   - ctx
//   - isActive
func (_e *MockStore_Expecter) CountRoom(ctx interface{}, isActive interface{}) *MockStore_CountRoom_Call {
	return &MockStore_CountRoom_Call{Call: _e.mock.On("CountRoom", ctx, isActive)}
}

func (_c *MockStore_CountRoom_Call) Run(run func(ctx context.Context, isActive sql.NullBool)) *MockStore_CountRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql.NullBool))
	})
	return _c
}

func (_c *MockStore_CountRoom_Call) Return(n int64, err error) *MockStore_CountRoom_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_CountRoom_Call) RunAndReturn(run func(ctx context.Context, isActive sql.NullBool) (int64, error)) *MockStore_CountRoom_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReservation provides a mock function for the type MockStore
func (_mock *MockStore) CreateReservation(ctx context.Context, arg db.CreateReservationParams) (db.Reservation, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 db.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateReservationParams) (db.Reservation, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateReservationParams) db.Reservation); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateReservationParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReservation'
type MockStore_CreateReservation_Call struct {
	*mock.Call
}

// CreateReservation is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) CreateReservation(ctx interface{}, arg interface{}) *MockStore_CreateReservation_Call {
	return &MockStore_CreateReservation_Call{Call: _e.mock.On("CreateReservation", ctx, arg)}
}

func (_c *MockStore_CreateReservation_Call) Run(run func(ctx context.Context, arg db.CreateReservationParams)) *MockStore_CreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateReservationParams))
	})
	return _c
}

func (_c *MockStore_CreateReservation_Call) Return(reservation db.Reservation, err error) *MockStore_CreateReservation_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *MockStore_CreateReservation_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateReservationParams) (db.Reservation, error)) *MockStore_CreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoom provides a mock function for the type MockStore
func (_mock *MockStore) CreateRoom(ctx context.Context, arg db.CreateRoomParams) (db.Room, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 db.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) (db.Room, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) db.Room); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Room)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateRoomParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockStore_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) CreateRoom(ctx interface{}, arg interface{}) *MockStore_CreateRoom_Call {
	return &MockStore_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, arg)}
}

func (_c *MockStore_CreateRoom_Call) Run(run func(ctx context.Context, arg db.CreateRoomParams)) *MockStore_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateRoomParams))
	})
	return _c
}

func (_c *MockStore_CreateRoom_Call) Return(room db.Room, err error) *MockStore_CreateRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockStore_CreateRoom_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateRoomParams) (db.Room, error)) *MockStore_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSeat provides a mock function for the type MockStore
func (_mock *MockStore) CreateSeat(ctx context.Context, arg db.CreateSeatParams) (db.Seat, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeat")
	}

	var r0 db.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateSeatParams) (db.Seat, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateSeatParams) db.Seat); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Seat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateSeatParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateSeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeat'
type MockStore_CreateSeat_Call struct {
	*mock.Call
}

// CreateSeat is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) CreateSeat(ctx interface{}, arg interface{}) *MockStore_CreateSeat_Call {
	return &MockStore_CreateSeat_Call{Call: _e.mock.On("CreateSeat", ctx, arg)}
}

func (_c *MockStore_CreateSeat_Call) Run(run func(ctx context.Context, arg db.CreateSeatParams)) *MockStore_CreateSeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateSeatParams))
	})
	return _c
}

func (_c *MockStore_CreateSeat_Call) Return(seat db.Seat, err error) *MockStore_CreateSeat_Call {
	_c.Call.Return(seat, err)
	return _c
}

func (_c *MockStore_CreateSeat_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateSeatParams) (db.Seat, error)) *MockStore_CreateSeat_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSeats provides a mock function for the type MockStore
func (_mock *MockStore) CreateSeats(ctx context.Context, arg db.CreateSeatsParams) ([]db.Seat, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeats")
	}

	var r0 []db.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateSeatsParams) ([]db.Seat, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateSeatsParams) []db.Seat); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Seat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateSeatsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateSeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeats'
type MockStore_CreateSeats_Call struct {
	*mock.Call
}

// CreateSeats is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) CreateSeats(ctx interface{}, arg interface{}) *MockStore_CreateSeats_Call {
	return &MockStore_CreateSeats_Call{Call: _e.mock.On("CreateSeats", ctx, arg)}
}

func (_c *MockStore_CreateSeats_Call) Run(run func(ctx context.Context, arg db.CreateSeatsParams)) *MockStore_CreateSeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateSeatsParams))
	})
	return _c
}

func (_c *MockStore_CreateSeats_Call) Return(seats []db.Seat, err error) *MockStore_CreateSeats_Call {
	_c.Call.Return(seats, err)
	return _c
}

func (_c *MockStore_CreateSeats_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateSeatsParams) ([]db.Seat, error)) *MockStore_CreateSeats_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockStore
func (_mock *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockStore_CreateUser_Call {
	return &MockStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockStore_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *MockStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockStore_CreateUser_Call) Return(user db.User, err error) *MockStore_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateUserParams) (db.User, error)) *MockStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateViolation provides a mock function for the type MockStore
func (_mock *MockStore) CreateViolation(ctx context.Context, arg db.CreateViolationParams) (db.Violation, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateViolation")
	}

	var r0 db.Violation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateViolationParams) (db.Violation, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateViolationParams) db.Violation); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Violation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateViolationParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateViolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateViolation'
type MockStore_CreateViolation_Call struct {
	*mock.Call
}

// CreateViolation is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) CreateViolation(ctx interface{}, arg interface{}) *MockStore_CreateViolation_Call {
	return &MockStore_CreateViolation_Call{Call: _e.mock.On("CreateViolation", ctx, arg)}
}

func (_c *MockStore_CreateViolation_Call) Run(run func(ctx context.Context, arg db.CreateViolationParams)) *MockStore_CreateViolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateViolationParams))
	})
	return _c
}

func (_c *MockStore_CreateViolation_Call) Return(violation db.Violation, err error) *MockStore_CreateViolation_Call {
	_c.Call.Return(violation, err)
	return _c
}

func (_c *MockStore_CreateViolation_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateViolationParams) (db.Violation, error)) *MockStore_CreateViolation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReservation provides a mock function for the type MockStore
func (_mock *MockStore) DeleteReservation(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReservation")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (sql.Result, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) sql.Result); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_DeleteReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReservation'
type MockStore_DeleteReservation_Call struct {
	*mock.Call
}

// DeleteReservation is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) DeleteReservation(ctx interface{}, id interface{}) *MockStore_DeleteReservation_Call {
	return &MockStore_DeleteReservation_Call{Call: _e.mock.On("DeleteReservation", ctx, id)}
}

func (_c *MockStore_DeleteReservation_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_DeleteReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_DeleteReservation_Call) Return(result sql.Result, err error) *MockStore_DeleteReservation_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockStore_DeleteReservation_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (sql.Result, error)) *MockStore_DeleteReservation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function for the type MockStore
func (_mock *MockStore) DeleteRoom(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type MockStore_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) DeleteRoom(ctx interface{}, id interface{}) *MockStore_DeleteRoom_Call {
	return &MockStore_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom", ctx, id)}
}

func (_c *MockStore_DeleteRoom_Call) Run(run func(ctx context.Context, id int32)) *MockStore_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_DeleteRoom_Call) Return(err error) *MockStore_DeleteRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteRoom_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *MockStore_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSeat provides a mock function for the type MockStore
func (_mock *MockStore) DeleteSeat(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSeat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteSeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSeat'
type MockStore_DeleteSeat_Call struct {
	*mock.Call
}

// DeleteSeat is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) DeleteSeat(ctx interface{}, id interface{}) *MockStore_DeleteSeat_Call {
	return &MockStore_DeleteSeat_Call{Call: _e.mock.On("DeleteSeat", ctx, id)}
}

func (_c *MockStore_DeleteSeat_Call) Run(run func(ctx context.Context, id int32)) *MockStore_DeleteSeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_DeleteSeat_Call) Return(err error) *MockStore_DeleteSeat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteSeat_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *MockStore_DeleteSeat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockStore
func (_mock *MockStore) DeleteUser(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockStore_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockStore_DeleteUser_Call {
	return &MockStore_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockStore_DeleteUser_Call) Run(run func(ctx context.Context, id int32)) *MockStore_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_DeleteUser_Call) Return(err error) *MockStore_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *MockStore_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireReservations provides a mock function for the type MockStore
func (_mock *MockStore) ExpireReservations(ctx context.Context, dollar_1 sql.NullString) ([]db.ExpireReservationsRow, error) {
	ret := _mock.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ExpireReservations")
	}

	var r0 []db.ExpireReservationsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, sql.NullString) ([]db.ExpireReservationsRow, error)); ok {
		return returnFunc(ctx, dollar_1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, sql.NullString) []db.ExpireReservationsRow); ok {
		r0 = returnFunc(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ExpireReservationsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, sql.NullString) error); ok {
		r1 = returnFunc(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ExpireReservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireReservations'
type MockStore_ExpireReservations_Call struct {
	*mock.Call
}

// ExpireReservations is a helper method to define mock.On call
//   - ctx
//   - dollar_1
func (_e *MockStore_Expecter) ExpireReservations(ctx interface{}, dollar_1 interface{}) *MockStore_ExpireReservations_Call {
	return &MockStore_ExpireReservations_Call{Call: _e.mock.On("ExpireReservations", ctx, dollar_1)}
}

func (_c *MockStore_ExpireReservations_Call) Run(run func(ctx context.Context, dollar_1 sql.NullString)) *MockStore_ExpireReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sql.NullString))
	})
	return _c
}

func (_c *MockStore_ExpireReservations_Call) Return(expireReservationsRows []db.ExpireReservationsRow, err error) *MockStore_ExpireReservations_Call {
	_c.Call.Return(expireReservationsRows, err)
	return _c
}

func (_c *MockStore_ExpireReservations_Call) RunAndReturn(run func(ctx context.Context, dollar_1 sql.NullString) ([]db.ExpireReservationsRow, error)) *MockStore_ExpireReservations_Call {
	_c.Call.Return(run)
	return _c
}

// GetReservation provides a mock function for the type MockStore
func (_mock *MockStore) GetReservation(ctx context.Context, id uuid.UUID) (db.Reservation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReservation")
	}

	var r0 db.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.Reservation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.Reservation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReservation'
type MockStore_GetReservation_Call struct {
	*mock.Call
}

// GetReservation is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetReservation(ctx interface{}, id interface{}) *MockStore_GetReservation_Call {
	return &MockStore_GetReservation_Call{Call: _e.mock.On("GetReservation", ctx, id)}
}

func (_c *MockStore_GetReservation_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockStore_GetReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetReservation_Call) Return(reservation db.Reservation, err error) *MockStore_GetReservation_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *MockStore_GetReservation_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (db.Reservation, error)) *MockStore_GetReservation_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function for the type MockStore
func (_mock *MockStore) GetRoom(ctx context.Context, id int32) (db.Room, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 db.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.Room, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.Room); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Room)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type MockStore_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetRoom(ctx interface{}, id interface{}) *MockStore_GetRoom_Call {
	return &MockStore_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, id)}
}

func (_c *MockStore_GetRoom_Call) Run(run func(ctx context.Context, id int32)) *MockStore_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_GetRoom_Call) Return(room db.Room, err error) *MockStore_GetRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockStore_GetRoom_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.Room, error)) *MockStore_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomUsage provides a mock function for the type MockStore
func (_mock *MockStore) GetRoomUsage(ctx context.Context) ([]db.GetRoomUsageRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomUsage")
	}

	var r0 []db.GetRoomUsageRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]db.GetRoomUsageRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []db.GetRoomUsageRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetRoomUsageRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRoomUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomUsage'
type MockStore_GetRoomUsage_Call struct {
	*mock.Call
}

// GetRoomUsage is a helper method to define mock.On call
//   - ctx
func (_e *MockStore_Expecter) GetRoomUsage(ctx interface{}) *MockStore_GetRoomUsage_Call {
	return &MockStore_GetRoomUsage_Call{Call: _e.mock.On("GetRoomUsage", ctx)}
}

func (_c *MockStore_GetRoomUsage_Call) Run(run func(ctx context.Context)) *MockStore_GetRoomUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_GetRoomUsage_Call) Return(getRoomUsageRows []db.GetRoomUsageRow, err error) *MockStore_GetRoomUsage_Call {
	_c.Call.Return(getRoomUsageRows, err)
	return _c
}

func (_c *MockStore_GetRoomUsage_Call) RunAndReturn(run func(ctx context.Context) ([]db.GetRoomUsageRow, error)) *MockStore_GetRoomUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeat provides a mock function for the type MockStore
func (_mock *MockStore) GetSeat(ctx context.Context, id int32) (db.Seat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSeat")
	}

	var r0 db.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.Seat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.Seat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Seat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeat'
type MockStore_GetSeat_Call struct {
	*mock.Call
}

// GetSeat is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetSeat(ctx interface{}, id interface{}) *MockStore_GetSeat_Call {
	return &MockStore_GetSeat_Call{Call: _e.mock.On("GetSeat", ctx, id)}
}

func (_c *MockStore_GetSeat_Call) Run(run func(ctx context.Context, id int32)) *MockStore_GetSeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_GetSeat_Call) Return(seat db.Seat, err error) *MockStore_GetSeat_Call {
	_c.Call.Return(seat, err)
	return _c
}

func (_c *MockStore_GetSeat_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.Seat, error)) *MockStore_GetSeat_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeatWithRoom provides a mock function for the type MockStore
func (_mock *MockStore) GetSeatWithRoom(ctx context.Context, id int32) (db.GetSeatWithRoomRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSeatWithRoom")
	}

	var r0 db.GetSeatWithRoomRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.GetSeatWithRoomRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.GetSeatWithRoomRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetSeatWithRoomRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSeatWithRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeatWithRoom'
type MockStore_GetSeatWithRoom_Call struct {
	*mock.Call
}

// GetSeatWithRoom is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetSeatWithRoom(ctx interface{}, id interface{}) *MockStore_GetSeatWithRoom_Call {
	return &MockStore_GetSeatWithRoom_Call{Call: _e.mock.On("GetSeatWithRoom", ctx, id)}
}

func (_c *MockStore_GetSeatWithRoom_Call) Run(run func(ctx context.Context, id int32)) *MockStore_GetSeatWithRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_GetSeatWithRoom_Call) Return(getSeatWithRoomRow db.GetSeatWithRoomRow, err error) *MockStore_GetSeatWithRoom_Call {
	_c.Call.Return(getSeatWithRoomRow, err)
	return _c
}

func (_c *MockStore_GetSeatWithRoom_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.GetSeatWithRoomRow, error)) *MockStore_GetSeatWithRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockStore
func (_mock *MockStore) GetUser(ctx context.Context, id int32) (db.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetUser(ctx interface{}, id interface{}) *MockStore_GetUser_Call {
	return &MockStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockStore_GetUser_Call) Run(run func(ctx context.Context, id int32)) *MockStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_GetUser_Call) Return(user db.User, err error) *MockStore_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.User, error)) *MockStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBehaviorStats provides a mock function for the type MockStore
func (_mock *MockStore) GetUserBehaviorStats(ctx context.Context, id int32) (db.GetUserBehaviorStatsRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBehaviorStats")
	}

	var r0 db.GetUserBehaviorStatsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.GetUserBehaviorStatsRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.GetUserBehaviorStatsRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetUserBehaviorStatsRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetUserBehaviorStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBehaviorStats'
type MockStore_GetUserBehaviorStats_Call struct {
	*mock.Call
}

// GetUserBehaviorStats is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetUserBehaviorStats(ctx interface{}, id interface{}) *MockStore_GetUserBehaviorStats_Call {
	return &MockStore_GetUserBehaviorStats_Call{Call: _e.mock.On("GetUserBehaviorStats", ctx, id)}
}

func (_c *MockStore_GetUserBehaviorStats_Call) Run(run func(ctx context.Context, id int32)) *MockStore_GetUserBehaviorStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_GetUserBehaviorStats_Call) Return(getUserBehaviorStatsRow db.GetUserBehaviorStatsRow, err error) *MockStore_GetUserBehaviorStats_Call {
	_c.Call.Return(getUserBehaviorStatsRow, err)
	return _c
}

func (_c *MockStore_GetUserBehaviorStats_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.GetUserBehaviorStatsRow, error)) *MockStore_GetUserBehaviorStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockStore
func (_mock *MockStore) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockStore_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx
//   - username
func (_e *MockStore_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockStore_GetUserByUsername_Call {
	return &MockStore_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockStore_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockStore_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUserByUsername_Call) Return(user db.User, err error) *MockStore_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (db.User, error)) *MockStore_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetViolation provides a mock function for the type MockStore
func (_mock *MockStore) GetViolation(ctx context.Context, id int32) (db.Violation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetViolation")
	}

	var r0 db.Violation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.Violation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.Violation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Violation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetViolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetViolation'
type MockStore_GetViolation_Call struct {
	*mock.Call
}

// GetViolation is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockStore_Expecter) GetViolation(ctx interface{}, id interface{}) *MockStore_GetViolation_Call {
	return &MockStore_GetViolation_Call{Call: _e.mock.On("GetViolation", ctx, id)}
}

func (_c *MockStore_GetViolation_Call) Run(run func(ctx context.Context, id int32)) *MockStore_GetViolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockStore_GetViolation_Call) Return(violation db.Violation, err error) *MockStore_GetViolation_Call {
	_c.Call.Return(violation, err)
	return _c
}

func (_c *MockStore_GetViolation_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.Violation, error)) *MockStore_GetViolation_Call {
	_c.Call.Return(run)
	return _c
}

// ListReservation provides a mock function for the type MockStore
func (_mock *MockStore) ListReservation(ctx context.Context, arg db.ListReservationParams) ([]db.Reservation, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListReservation")
	}

	var r0 []db.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListReservationParams) ([]db.Reservation, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListReservationParams) []db.Reservation); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListReservationParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReservation'
type MockStore_ListReservation_Call struct {
	*mock.Call
}

// ListReservation is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) ListReservation(ctx interface{}, arg interface{}) *MockStore_ListReservation_Call {
	return &MockStore_ListReservation_Call{Call: _e.mock.On("ListReservation", ctx, arg)}
}

func (_c *MockStore_ListReservation_Call) Run(run func(ctx context.Context, arg db.ListReservationParams)) *MockStore_ListReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListReservationParams))
	})
	return _c
}

func (_c *MockStore_ListReservation_Call) Return(reservations []db.Reservation, err error) *MockStore_ListReservation_Call {
	_c.Call.Return(reservations, err)
	return _c
}

func (_c *MockStore_ListReservation_Call) RunAndReturn(run func(ctx context.Context, arg db.ListReservationParams) ([]db.Reservation, error)) *MockStore_ListReservation_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoom provides a mock function for the type MockStore
func (_mock *MockStore) ListRoom(ctx context.Context, arg db.ListRoomParams) ([]db.Room, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRoom")
	}

	var r0 []db.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRoomParams) ([]db.Room, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRoomParams) []db.Room); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListRoomParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoom'
type MockStore_ListRoom_Call struct {
	*mock.Call
}

// ListRoom is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) ListRoom(ctx interface{}, arg interface{}) *MockStore_ListRoom_Call {
	return &MockStore_ListRoom_Call{Call: _e.mock.On("ListRoom", ctx, arg)}
}

func (_c *MockStore_ListRoom_Call) Run(run func(ctx context.Context, arg db.ListRoomParams)) *MockStore_ListRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListRoomParams))
	})
	return _c
}

func (_c *MockStore_ListRoom_Call) Return(rooms []db.Room, err error) *MockStore_ListRoom_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockStore_ListRoom_Call) RunAndReturn(run func(ctx context.Context, arg db.ListRoomParams) ([]db.Room, error)) *MockStore_ListRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeat provides a mock function for the type MockStore
func (_mock *MockStore) ListSeat(ctx context.Context, arg db.ListSeatParams) ([]db.Seat, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListSeat")
	}

	var r0 []db.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListSeatParams) ([]db.Seat, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListSeatParams) []db.Seat); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Seat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListSeatParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListSeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeat'
type MockStore_ListSeat_Call struct {
	*mock.Call
}

// ListSeat is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) ListSeat(ctx interface{}, arg interface{}) *MockStore_ListSeat_Call {
	return &MockStore_ListSeat_Call{Call: _e.mock.On("ListSeat", ctx, arg)}
}

func (_c *MockStore_ListSeat_Call) Run(run func(ctx context.Context, arg db.ListSeatParams)) *MockStore_ListSeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListSeatParams))
	})
	return _c
}

func (_c *MockStore_ListSeat_Call) Return(seats []db.Seat, err error) *MockStore_ListSeat_Call {
	_c.Call.Return(seats, err)
	return _c
}

func (_c *MockStore_ListSeat_Call) RunAndReturn(run func(ctx context.Context, arg db.ListSeatParams) ([]db.Seat, error)) *MockStore_ListSeat_Call {
	_c.Call.Return(run)
	return _c
}

// ListUser provides a mock function for the type MockStore
func (_mock *MockStore) ListUser(ctx context.Context, arg db.ListUserParams) ([]db.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUser")
	}

	var r0 []db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListUserParams) ([]db.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListUserParams) []db.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUser'
type MockStore_ListUser_Call struct {
	*mock.Call
}

// ListUser is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) ListUser(ctx interface{}, arg interface{}) *MockStore_ListUser_Call {
	return &MockStore_ListUser_Call{Call: _e.mock.On("ListUser", ctx, arg)}
}

func (_c *MockStore_ListUser_Call) Run(run func(ctx context.Context, arg db.ListUserParams)) *MockStore_ListUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListUserParams))
	})
	return _c
}

func (_c *MockStore_ListUser_Call) Return(users []db.User, err error) *MockStore_ListUser_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockStore_ListUser_Call) RunAndReturn(run func(ctx context.Context, arg db.ListUserParams) ([]db.User, error)) *MockStore_ListUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListViolation provides a mock function for the type MockStore
func (_mock *MockStore) ListViolation(ctx context.Context, arg db.ListViolationParams) ([]db.Violation, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListViolation")
	}

	var r0 []db.Violation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListViolationParams) ([]db.Violation, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListViolationParams) []db.Violation); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Violation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListViolationParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListViolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListViolation'
type MockStore_ListViolation_Call struct {
	*mock.Call
}

// ListViolation is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) ListViolation(ctx interface{}, arg interface{}) *MockStore_ListViolation_Call {
	return &MockStore_ListViolation_Call{Call: _e.mock.On("ListViolation", ctx, arg)}
}

func (_c *MockStore_ListViolation_Call) Run(run func(ctx context.Context, arg db.ListViolationParams)) *MockStore_ListViolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ListViolationParams))
	})
	return _c
}

func (_c *MockStore_ListViolation_Call) Return(violations []db.Violation, err error) *MockStore_ListViolation_Call {
	_c.Call.Return(violations, err)
	return _c
}

func (_c *MockStore_ListViolation_Call) RunAndReturn(run func(ctx context.Context, arg db.ListViolationParams) ([]db.Violation, error)) *MockStore_ListViolation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAllRoomCode provides a mock function for the type MockStore
func (_mock *MockStore) UpdateAllRoomCode(ctx context.Context, codes []string) error {
	ret := _mock.Called(ctx, codes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllRoomCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, codes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_UpdateAllRoomCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAllRoomCode'
type MockStore_UpdateAllRoomCode_Call struct {
	*mock.Call
}

// UpdateAllRoomCode is a helper method to define mock.On call
//   - ctx
//   - codes
func (_e *MockStore_Expecter) UpdateAllRoomCode(ctx interface{}, codes interface{}) *MockStore_UpdateAllRoomCode_Call {
	return &MockStore_UpdateAllRoomCode_Call{Call: _e.mock.On("UpdateAllRoomCode", ctx, codes)}
}

func (_c *MockStore_UpdateAllRoomCode_Call) Run(run func(ctx context.Context, codes []string)) *MockStore_UpdateAllRoomCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockStore_UpdateAllRoomCode_Call) Return(err error) *MockStore_UpdateAllRoomCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_UpdateAllRoomCode_Call) RunAndReturn(run func(ctx context.Context, codes []string) error) *MockStore_UpdateAllRoomCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservationStatus provides a mock function for the type MockStore
func (_mock *MockStore) UpdateReservationStatus(ctx context.Context, arg db.UpdateReservationStatusParams) (db.Reservation, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservationStatus")
	}

	var r0 db.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateReservationStatusParams) (db.Reservation, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateReservationStatusParams) db.Reservation); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateReservationStatusParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateReservationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservationStatus'
type MockStore_UpdateReservationStatus_Call struct {
	*mock.Call
}

// UpdateReservationStatus is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) UpdateReservationStatus(ctx interface{}, arg interface{}) *MockStore_UpdateReservationStatus_Call {
	return &MockStore_UpdateReservationStatus_Call{Call: _e.mock.On("UpdateReservationStatus", ctx, arg)}
}

func (_c *MockStore_UpdateReservationStatus_Call) Run(run func(ctx context.Context, arg db.UpdateReservationStatusParams)) *MockStore_UpdateReservationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateReservationStatusParams))
	})
	return _c
}

func (_c *MockStore_UpdateReservationStatus_Call) Return(reservation db.Reservation, err error) *MockStore_UpdateReservationStatus_Call {
	_c.Call.Return(reservation, err)
	return _c
}

func (_c *MockStore_UpdateReservationStatus_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateReservationStatusParams) (db.Reservation, error)) *MockStore_UpdateReservationStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoom provides a mock function for the type MockStore
func (_mock *MockStore) UpdateRoom(ctx context.Context, arg db.UpdateRoomParams) (db.Room, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 db.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateRoomParams) (db.Room, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateRoomParams) db.Room); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Room)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateRoomParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoom'
type MockStore_UpdateRoom_Call struct {
	*mock.Call
}

// UpdateRoom is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) UpdateRoom(ctx interface{}, arg interface{}) *MockStore_UpdateRoom_Call {
	return &MockStore_UpdateRoom_Call{Call: _e.mock.On("UpdateRoom", ctx, arg)}
}

func (_c *MockStore_UpdateRoom_Call) Run(run func(ctx context.Context, arg db.UpdateRoomParams)) *MockStore_UpdateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateRoomParams))
	})
	return _c
}

func (_c *MockStore_UpdateRoom_Call) Return(room db.Room, err error) *MockStore_UpdateRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockStore_UpdateRoom_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateRoomParams) (db.Room, error)) *MockStore_UpdateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSeat provides a mock function for the type MockStore
func (_mock *MockStore) UpdateSeat(ctx context.Context, arg db.UpdateSeatParams) (db.Seat, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSeat")
	}

	var r0 db.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateSeatParams) (db.Seat, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateSeatParams) db.Seat); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Seat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateSeatParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateSeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSeat'
type MockStore_UpdateSeat_Call struct {
	*mock.Call
}

// UpdateSeat is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) UpdateSeat(ctx interface{}, arg interface{}) *MockStore_UpdateSeat_Call {
	return &MockStore_UpdateSeat_Call{Call: _e.mock.On("UpdateSeat", ctx, arg)}
}

func (_c *MockStore_UpdateSeat_Call) Run(run func(ctx context.Context, arg db.UpdateSeatParams)) *MockStore_UpdateSeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateSeatParams))
	})
	return _c
}

func (_c *MockStore_UpdateSeat_Call) Return(seat db.Seat, err error) *MockStore_UpdateSeat_Call {
	_c.Call.Return(seat, err)
	return _c
}

func (_c *MockStore_UpdateSeat_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateSeatParams) (db.Seat, error)) *MockStore_UpdateSeat_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSeats provides a mock function for the type MockStore
func (_mock *MockStore) UpdateSeats(ctx context.Context, arg db.UpdateSeatsParams) ([]db.Seat, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSeats")
	}

	var r0 []db.Seat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateSeatsParams) ([]db.Seat, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateSeatsParams) []db.Seat); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Seat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateSeatsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateSeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSeats'
type MockStore_UpdateSeats_Call struct {
	*mock.Call
}

// UpdateSeats is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) UpdateSeats(ctx interface{}, arg interface{}) *MockStore_UpdateSeats_Call {
	return &MockStore_UpdateSeats_Call{Call: _e.mock.On("UpdateSeats", ctx, arg)}
}

func (_c *MockStore_UpdateSeats_Call) Run(run func(ctx context.Context, arg db.UpdateSeatsParams)) *MockStore_UpdateSeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateSeatsParams))
	})
	return _c
}

func (_c *MockStore_UpdateSeats_Call) Return(seats []db.Seat, err error) *MockStore_UpdateSeats_Call {
	_c.Call.Return(seats, err)
	return _c
}

func (_c *MockStore_UpdateSeats_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateSeatsParams) ([]db.Seat, error)) *MockStore_UpdateSeats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockStore
func (_mock *MockStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) (db.User, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) db.User); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockStore_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) UpdateUser(ctx interface{}, arg interface{}) *MockStore_UpdateUser_Call {
	return &MockStore_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *MockStore_UpdateUser_Call) Run(run func(ctx context.Context, arg db.UpdateUserParams)) *MockStore_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserParams))
	})
	return _c
}

func (_c *MockStore_UpdateUser_Call) Return(user db.User, err error) *MockStore_UpdateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateUserParams) (db.User, error)) *MockStore_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateViolation provides a mock function for the type MockStore
func (_mock *MockStore) UpdateViolation(ctx context.Context, arg db.UpdateViolationParams) (db.Violation, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateViolation")
	}

	var r0 db.Violation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateViolationParams) (db.Violation, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateViolationParams) db.Violation); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Violation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.UpdateViolationParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateViolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateViolation'
type MockStore_UpdateViolation_Call struct {
	*mock.Call
}

// UpdateViolation is a helper method to define mock.On call
//   - ctx
//   - arg
func (_e *MockStore_Expecter) UpdateViolation(ctx interface{}, arg interface{}) *MockStore_UpdateViolation_Call {
	return &MockStore_UpdateViolation_Call{Call: _e.mock.On("UpdateViolation", ctx, arg)}
}

func (_c *MockStore_UpdateViolation_Call) Run(run func(ctx context.Context, arg db.UpdateViolationParams)) *MockStore_UpdateViolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateViolationParams))
	})
	return _c
}

func (_c *MockStore_UpdateViolation_Call) Return(violation db.Violation, err error) *MockStore_UpdateViolation_Call {
	_c.Call.Return(violation, err)
	return _c
}

func (_c *MockStore_UpdateViolation_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateViolationParams) (db.Violation, error)) *MockStore_UpdateViolation_Call {
	_c.Call.Return(run)
	return _c
}
