all: false
dir: db/mock
filename: mocks_test.go
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: mock
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  man/db:
    interfaces:
      Store:
