# 注意没有使用volumes，数据会丢失
name: management
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: man
    networks:
      - management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d man"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - management
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - DB_SOURCE=postgresql://admin:admin@db:5432/man?sslmode=disable

networks:
  management:
    driver: bridge