// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ReservationStatus string

const (
	ReservationStatusReserved  ReservationStatus = "reserved"
	ReservationStatusCompleted ReservationStatus = "completed"
	ReservationStatusCanceled  ReservationStatus = "canceled"
	ReservationStatusViolated  ReservationStatus = "violated"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type Reservation struct {
	ID          uuid.UUID         `json:"id"`
	UserID      int32             `json:"user_id"`
	SeatID      int32             `json:"seat_id"`
	StartTime   time.Time         `json:"start_time"`
	EndTime     time.Time         `json:"end_time"`
	Status      ReservationStatus `json:"status"`
	CheckinTime time.Time         `json:"checkin_time"`
	CreatedAt   time.Time         `json:"created_at"`
}

type Room struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	Department string    `json:"department"`
	OpenTime   time.Time `json:"open_time"`
	CloseTime  time.Time `json:"close_time"`
	Code       string    `json:"code"`
	QrCode     string    `json:"qr_code"`
	IsActive   bool      `json:"is_active"`
}

type Seat struct {
	ID          int32  `json:"id"`
	RoomID      int32  `json:"room_id"`
	Number      string `json:"number"`
	HasSocket   bool   `json:"has_socket"`
	IsAvailable bool   `json:"is_available"`
}

type User struct {
	ID         int32     `json:"id"`
	Username   string    `json:"username"`
	Password   string    `json:"password"`
	Role       string    `json:"role"`
	Department string    `json:"department"`
	Email      string    `json:"email"`
	CreatedAt  time.Time `json:"created_at"`
}

type Violation struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
	Reason        string    `json:"reason"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
}
