// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Reservation struct {
	ID          uuid.UUID `json:"id"`
	UserID      int32     `json:"user_id"`
	SeatID      int32     `json:"seat_id"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	Status      string    `json:"status"`
	CheckinTime time.Time `json:"checkin_time"`
	CreatedAt   time.Time `json:"created_at"`
}

type Room struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	Department string    `json:"department"`
	OpenTime   time.Time `json:"open_time"`
	CloseTime  time.Time `json:"close_time"`
	Code       string    `json:"code"`
	QrCode     string    `json:"qr_code"`
	IsActive   bool      `json:"is_active"`
}

type Seat struct {
	ID          int32  `json:"id"`
	RoomID      int32  `json:"room_id"`
	Number      string `json:"number"`
	HasSocket   bool   `json:"has_socket"`
	IsAvailable bool   `json:"is_available"`
}

type User struct {
	ID         int32     `json:"id"`
	Username   string    `json:"username"`
	Password   string    `json:"password"`
	Role       string    `json:"role"`
	Department string    `json:"department"`
	Email      string    `json:"email"`
	CreatedAt  time.Time `json:"created_at"`
}

type Violation struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
	Reason        string    `json:"reason"`
	CreatedAt     time.Time `json:"created_at"`
}
