// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	// 创建带时间冲突检测的预约
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// 创建关联预约的违约记录
	CreateViolationWithCheck(ctx context.Context, arg CreateViolationWithCheckParams) (Violation, error)
	DeleteSeat(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	// 参数化超时时间（分钟）
	ExpireReservations(ctx context.Context, dollar_1 sql.NullString) ([]ExpireReservationsRow, error)
	GetReservation(ctx context.Context, id uuid.UUID) (Reservation, error)
	GetRoom(ctx context.Context, id int32) (Room, error)
	// 自习室实时使用统计（含插座统计）
	GetRoomUtilization(ctx context.Context) ([]GetRoomUtilizationRow, error)
	GetSeat(ctx context.Context, id int32) (Seat, error)
	// 获取座位详细信息（含自习室信息）
	GetSeatWithRoom(ctx context.Context, id int32) (GetSeatWithRoomRow, error)
	GetUser(ctx context.Context, id int32) (User, error)
	// 用户行为分析（含预约和违约统计）
	GetUserBehaviorStats(ctx context.Context, id int32) (GetUserBehaviorStatsRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// 通用查询, 可能参数start_time, end_time, limit, offset, user_id, seat_id, status
	ListReservation(ctx context.Context, arg ListReservationParams) ([]Reservation, error)
	// department,is_active作为可能查询条件
	ListRoom(ctx context.Context, arg ListRoomParams) ([]Room, error)
	// 获取自习室的座位列表
	ListRoomSeat(ctx context.Context, roomID int32) ([]Seat, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	// 获取用户违约详情（含预约信息）
	ListUserViolation(ctx context.Context, userID int32) ([]ListUserViolationRow, error)
	// 更新预约状态（含自动签到时间）
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error)
	// 批量更新座位
	UpdateSeats(ctx context.Context, arg UpdateSeatsParams) ([]Seat, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
