// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	// 获取自习室数量
	// 可选参数：is_active
	CountRoom(ctx context.Context, isActive sql.NullBool) (int64, error)
	// 创建预约
	// 预约时间段内不能有其他预约，且座位必须可用
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	// 创建自习室，不考虑二维码/签到码
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	// 创建座位表
	CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error)
	// 创建座位表（批量插入）
	CreateSeats(ctx context.Context, arg CreateSeatsParams) ([]Seat, error)
	// 插入用户数据到"user"表
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// 创建关联预约的违约记录
	CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error)
	// 删除预约（只能删除未开始的预约，如果已经到了预约时间，不能删除）
	DeleteReservation(ctx context.Context, id uuid.UUID) error
	// 删除自习室
	DeleteRoom(ctx context.Context, id int32) error
	// 删除座位
	DeleteSeat(ctx context.Context, id int32) error
	// 删除用户
	DeleteUser(ctx context.Context, id int32) error
	// 预约超时处理，将超时未签到的预约标记为违约
	// 参数为：超时时间（分钟）
	ExpireReservations(ctx context.Context, dollar_1 sql.NullString) ([]ExpireReservationsRow, error)
	GetReservation(ctx context.Context, id uuid.UUID) (Reservation, error)
	// 获取自习室信息
	GetRoom(ctx context.Context, id int32) (Room, error)
	// 自习室实时使用统计（含插座统计）
	GetRoomUsage(ctx context.Context) ([]GetRoomUsageRow, error)
	// 获取所有座位信息
	GetSeat(ctx context.Context, id int32) (Seat, error)
	// 获取座位详细信息（含自习室信息）
	GetSeatWithRoom(ctx context.Context, id int32) (GetSeatWithRoomRow, error)
	// 获取用户信息（通过ID）
	GetUser(ctx context.Context, id int32) (User, error)
	// 用户行为分析（含预约和违约统计）
	GetUserBehaviorStats(ctx context.Context, id int32) (GetUserBehaviorStatsRow, error)
	// 根据用户名获取用户信息
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// 获取违约记录
	GetViolation(ctx context.Context, id int32) (Violation, error)
	// 动态查询, 可能参数start_time, end_time, limit, offset, user_id, seat_id, status
	ListReservation(ctx context.Context, arg ListReservationParams) ([]Reservation, error)
	// department,is_active作为可能查询条件
	ListRoom(ctx context.Context, arg ListRoomParams) ([]Room, error)
	// 动态查询座位，可能参数room_id, has_socket, is_available
	ListSeat(ctx context.Context, arg ListSeatParams) ([]Seat, error)
	// 动态查询，可能参数role, department
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	// 动态查询，可能参数reservation_id, user_id
	ListViolation(ctx context.Context, arg ListViolationParams) ([]Violation, error)
	// 更新所有自习室签到码
	UpdateAllRoomCode(ctx context.Context, codes []string) error
	// 更新预约状态（含自动签到时间）
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
	// 更新自习室信息
	// 签到码和二维码自动生成，无需更新
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	// 更新座位信息
	// 主要用于用户预约座位时，更新座位的可用性
	UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error)
	// 批量更新座位, 不允许更改room_id
	UpdateSeats(ctx context.Context, arg UpdateSeatsParams) ([]Seat, error)
	// 更新用户信息
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// 更新违约记录
	UpdateViolation(ctx context.Context, arg UpdateViolationParams) (Violation, error)
}

var _ Querier = (*Queries)(nil)
