// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reservation.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservation (user_id, seat_id, start_time, end_time)
SELECT $1, $2, $3, $4
WHERE NOT EXISTS (
    SELECT 1 FROM reservation 
    WHERE seat_id = $2
    AND start_time < $4 
    AND end_time > $3
    AND status IN ('reserved', 'completed')
)
AND EXISTS (
    SELECT 1 FROM seat 
    WHERE id = $2 AND is_available = TRUE
)
RETURNING id, user_id, seat_id, start_time, end_time, status, checkin_time, created_at
`

type CreateReservationParams struct {
	UserID    int32     `json:"user_id"`
	SeatID    int32     `json:"seat_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// 创建预约
// 预约时间段内不能有其他预约，且座位必须可用
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation,
		arg.UserID,
		arg.SeatID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CheckinTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :execresult
UPDATE reservation
SET status = 'canceled'
WHERE id = $1 AND start_time > CURRENT_TIMESTAMP AND status = 'reserved'
`

// 取消预约（只能取消未开始的预约）
func (q *Queries) DeleteReservation(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteReservation, id)
}

const getReservation = `-- name: GetReservation :one
SELECT id, user_id, seat_id, start_time, end_time, status, checkin_time, created_at FROM reservation WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CheckinTime,
		&i.CreatedAt,
	)
	return i, err
}

const listReservation = `-- name: ListReservation :many
SELECT id, user_id, seat_id, start_time, end_time, status, checkin_time, created_at FROM reservation 
WHERE
  ($3::TIMESTAMP IS NULL OR start_time >= $3) AND
  ($4::TIMESTAMP IS NULL OR end_time <= $4) AND
  ($5::INT IS NULL OR user_id = $5) AND
  ($6::INT IS NULL OR seat_id = $6) AND
  ($7::VARCHAR(20) IS NULL OR status = $7)
ORDER BY
  CASE WHEN $8 = 'start_time' THEN start_time END DESC,
  created_at DESC
LIMIT $1 OFFSET $2
`

type ListReservationParams struct {
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
	StartTime sql.NullTime   `json:"start_time"`
	EndTime   sql.NullTime   `json:"end_time"`
	UserID    sql.NullInt32  `json:"user_id"`
	SeatID    sql.NullInt32  `json:"seat_id"`
	Status    sql.NullString `json:"status"`
	SortBy    interface{}    `json:"sort_by"`
}

// 动态查询, 可能参数start_time, end_time, limit, offset, user_id, seat_id, status
func (q *Queries) ListReservation(ctx context.Context, arg ListReservationParams) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listReservation,
		arg.Limit,
		arg.Offset,
		arg.StartTime,
		arg.EndTime,
		arg.UserID,
		arg.SeatID,
		arg.Status,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SeatID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CheckinTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservation SET
    status = $2,
    checkin_time = CASE 
        WHEN $2 = 'completed' THEN CURRENT_TIMESTAMP
        ELSE checkin_time 
    END
WHERE id = $1
RETURNING id, user_id, seat_id, start_time, end_time, status, checkin_time, created_at
`

type UpdateReservationStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status ReservationStatus `json:"status"`
}

// 更新预约状态（含自动签到时间）
func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, updateReservationStatus, arg.ID, arg.Status)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeatID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CheckinTime,
		&i.CreatedAt,
	)
	return i, err
}
