// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: room.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO room (name, department, open_time, close_time)
VALUES ($1, $2, $3, $4)
RETURNING id, name, department, open_time, close_time, code, qr_code, is_active
`

type CreateRoomParams struct {
	Name       string    `json:"name"`
	Department string    `json:"department"`
	OpenTime   time.Time `json:"open_time"`
	CloseTime  time.Time `json:"close_time"`
}

// 创建自习室，不考虑二维码/签到码
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.Name,
		arg.Department,
		arg.OpenTime,
		arg.CloseTime,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Department,
		&i.OpenTime,
		&i.CloseTime,
		&i.Code,
		&i.QrCode,
		&i.IsActive,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM room
WHERE id = $1
`

// 删除自习室
func (q *Queries) DeleteRoom(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, department, open_time, close_time, code, qr_code, is_active FROM room WHERE id = $1 LIMIT 1
`

// 获取自习室信息
func (q *Queries) GetRoom(ctx context.Context, id int32) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Department,
		&i.OpenTime,
		&i.CloseTime,
		&i.Code,
		&i.QrCode,
		&i.IsActive,
	)
	return i, err
}

const listRoom = `-- name: ListRoom :many
SELECT id, name, department, open_time, close_time, code, qr_code, is_active FROM room 
WHERE
  ($3::VARCHAR(50) IS NULL OR department = $3) AND
  ($4::BOOLEAN IS NULL OR is_active = $4)
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListRoomParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	Department sql.NullString `json:"department"`
	IsActive   sql.NullBool   `json:"is_active"`
}

// department,is_active作为可能查询条件
func (q *Queries) ListRoom(ctx context.Context, arg ListRoomParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRoom,
		arg.Limit,
		arg.Offset,
		arg.Department,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Department,
			&i.OpenTime,
			&i.CloseTime,
			&i.Code,
			&i.QrCode,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE room SET
    name = COALESCE($2, name),
    department = COALESCE($3, department),
    open_time = COALESCE($4, open_time),
    close_time = COALESCE($5, close_time),
    -- qr_code = COALESCE(sqlc.narg(qr_code), qr_code),
    -- code = COALESCE(sqlc.narg(code), code),
    is_active = COALESCE($6, is_active)
WHERE id = $1
RETURNING id, name, department, open_time, close_time, code, qr_code, is_active
`

type UpdateRoomParams struct {
	ID         int32          `json:"id"`
	Name       sql.NullString `json:"name"`
	Department sql.NullString `json:"department"`
	OpenTime   sql.NullTime   `json:"open_time"`
	CloseTime  sql.NullTime   `json:"close_time"`
	IsActive   sql.NullBool   `json:"is_active"`
}

// 更新自习室信息
// 签到码和二维码自动生成，无需更新
func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Department,
		arg.OpenTime,
		arg.CloseTime,
		arg.IsActive,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Department,
		&i.OpenTime,
		&i.CloseTime,
		&i.Code,
		&i.QrCode,
		&i.IsActive,
	)
	return i, err
}
