// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: seat.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createSeat = `-- name: CreateSeat :one
INSERT INTO seat (room_id, number, has_socket, is_available)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, number, has_socket, is_available
`

type CreateSeatParams struct {
	RoomID      int32  `json:"room_id"`
	Number      string `json:"number"`
	HasSocket   bool   `json:"has_socket"`
	IsAvailable bool   `json:"is_available"`
}

// 创建座位表
func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRowContext(ctx, createSeat,
		arg.RoomID,
		arg.Number,
		arg.HasSocket,
		arg.IsAvailable,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.HasSocket,
		&i.IsAvailable,
	)
	return i, err
}

const createSeats = `-- name: CreateSeats :many
INSERT INTO seat (room_id, number, has_socket, is_available)
SELECT 
    $1, 
    data.number, 
    data.has_socket, 
    data.is_available
FROM (
    SELECT 
        unnest($2::text[]) AS number,
        unnest($3::boolean[]) AS has_socket,
        unnest($4::boolean[]) AS is_available
) AS data
RETURNING id, room_id, number, has_socket, is_available
`

type CreateSeatsParams struct {
	RoomID       int32    `json:"room_id"`
	Numbers      []string `json:"numbers"`
	HasSockets   []bool   `json:"has_sockets"`
	IsAvailables []bool   `json:"is_availables"`
}

// 创建座位表（批量插入）
func (q *Queries) CreateSeats(ctx context.Context, arg CreateSeatsParams) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, createSeats,
		arg.RoomID,
		pq.Array(arg.Numbers),
		pq.Array(arg.HasSockets),
		pq.Array(arg.IsAvailables),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Number,
			&i.HasSocket,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSeat = `-- name: DeleteSeat :exec
DELETE FROM seat
WHERE id = $1
`

// 删除座位
func (q *Queries) DeleteSeat(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSeat, id)
	return err
}

const getSeat = `-- name: GetSeat :one
SELECT id, room_id, number, has_socket, is_available FROM seat
WHERE id = $1 LIMIT 1
`

// 获取所有座位信息
func (q *Queries) GetSeat(ctx context.Context, id int32) (Seat, error) {
	row := q.db.QueryRowContext(ctx, getSeat, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.HasSocket,
		&i.IsAvailable,
	)
	return i, err
}

const getSeatWithRoom = `-- name: GetSeatWithRoom :one
SELECT s.id, s.room_id, s.number, s.has_socket, s.is_available, r.name as room_name, r.open_time, r.close_time 
FROM seat s
JOIN room r ON s.room_id = r.id
WHERE s.id = $1
`

type GetSeatWithRoomRow struct {
	ID          int32     `json:"id"`
	RoomID      int32     `json:"room_id"`
	Number      string    `json:"number"`
	HasSocket   bool      `json:"has_socket"`
	IsAvailable bool      `json:"is_available"`
	RoomName    string    `json:"room_name"`
	OpenTime    time.Time `json:"open_time"`
	CloseTime   time.Time `json:"close_time"`
}

// 获取座位详细信息（含自习室信息）
func (q *Queries) GetSeatWithRoom(ctx context.Context, id int32) (GetSeatWithRoomRow, error) {
	row := q.db.QueryRowContext(ctx, getSeatWithRoom, id)
	var i GetSeatWithRoomRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.HasSocket,
		&i.IsAvailable,
		&i.RoomName,
		&i.OpenTime,
		&i.CloseTime,
	)
	return i, err
}

const listSeat = `-- name: ListSeat :many
SELECT s.id, s.room_id, s.number, s.has_socket, s.is_available FROM seat s
WHERE 
    ($3::INT IS NULL OR s.room_id = $3) AND
    ($4::BOOLEAN IS NULL OR s.has_socket = $4) AND
    ($5::BOOLEAN IS NULL OR s.is_available = $5)
ORDER BY s.room_id, s.id
LIMIT $1 OFFSET $2
`

type ListSeatParams struct {
	Limit       int32         `json:"limit"`
	Offset      int32         `json:"offset"`
	RoomID      sql.NullInt32 `json:"room_id"`
	HasSocket   sql.NullBool  `json:"has_socket"`
	IsAvailable sql.NullBool  `json:"is_available"`
}

// 动态查询座位，可能参数room_id, has_socket, is_available
func (q *Queries) ListSeat(ctx context.Context, arg ListSeatParams) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, listSeat,
		arg.Limit,
		arg.Offset,
		arg.RoomID,
		arg.HasSocket,
		arg.IsAvailable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Number,
			&i.HasSocket,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeat = `-- name: UpdateSeat :one
UPDATE seat SET
    number = COALESCE($2, number),
    has_socket = COALESCE($3, has_socket),
    is_available = COALESCE($4, is_available)
WHERE id = $1
RETURNING id, room_id, number, has_socket, is_available
`

type UpdateSeatParams struct {
	ID          int32          `json:"id"`
	Number      sql.NullString `json:"number"`
	HasSocket   sql.NullBool   `json:"has_socket"`
	IsAvailable sql.NullBool   `json:"is_available"`
}

// 更新座位信息
// 主要用于用户预约座位时，更新座位的可用性
func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error) {
	row := q.db.QueryRowContext(ctx, updateSeat,
		arg.ID,
		arg.Number,
		arg.HasSocket,
		arg.IsAvailable,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.HasSocket,
		&i.IsAvailable,
	)
	return i, err
}

const updateSeats = `-- name: UpdateSeats :many
UPDATE seat
SET
    number = data.number,
    has_socket = data.has_socket,
    is_available = data.is_available
FROM (
    SELECT unnest($1::int[]) AS id,
           unnest($2::text[]) AS number,
           unnest($3::boolean[]) AS has_socket,
           unnest($4::boolean[]) AS is_available
) AS data
WHERE seat.id = data.id
RETURNING seat.id, seat.room_id, seat.number, seat.has_socket, seat.is_available
`

type UpdateSeatsParams struct {
	Ids          []int32  `json:"ids"`
	Numbers      []string `json:"numbers"`
	HasSockets   []bool   `json:"has_sockets"`
	IsAvailables []bool   `json:"is_availables"`
}

// 批量更新座位, 不允许更改room_id
func (q *Queries) UpdateSeats(ctx context.Context, arg UpdateSeatsParams) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, updateSeats,
		pq.Array(arg.Ids),
		pq.Array(arg.Numbers),
		pq.Array(arg.HasSockets),
		pq.Array(arg.IsAvailables),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Number,
			&i.HasSocket,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
