// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: senior.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const expireReservations = `-- name: ExpireReservations :many
WITH expired_data AS (
    SELECT 
        r.id AS reservation_id,
        u.id AS user_id,
        u.email
    FROM reservation r
    JOIN "user" u ON r.user_id = u.id
    WHERE r.status = 'reserved'
    AND r.start_time < (NOW() - ($1 || ' minutes')::INTERVAL)
    FOR UPDATE SKIP LOCKED
    LIMIT 1000
),
insert_violation AS (
    INSERT INTO violation (user_id, reservation_id, reason)
    SELECT user_id, reservation_id, '超时未签到'
    FROM expired_data
    RETURNING reservation_id
)
UPDATE reservation r
SET status = 'violated'
FROM expired_data e
WHERE r.id = e.reservation_id
RETURNING e.reservation_id, e.user_id, e.email
`

type ExpireReservationsRow struct {
	ReservationID uuid.UUID `json:"reservation_id"`
	UserID        int32     `json:"user_id"`
	Email         string    `json:"email"`
}

// 参数化超时时间（分钟）
func (q *Queries) ExpireReservations(ctx context.Context, dollar_1 sql.NullString) ([]ExpireReservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, expireReservations, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireReservationsRow{}
	for rows.Next() {
		var i ExpireReservationsRow
		if err := rows.Scan(&i.ReservationID, &i.UserID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomUtilization = `-- name: GetRoomUtilization :many
SELECT 
    r.id,
    r.name,
    COUNT(s.id) FILTER (WHERE s.is_available) as available_seats,
    COUNT(s.id) FILTER (WHERE NOT s.is_available) as occupied_seats,
    COUNT(s.id) FILTER (WHERE s.has_socket) as socket_seats
FROM room r
LEFT JOIN seat s ON r.id = s.room_id
GROUP BY r.id, r.name
`

type GetRoomUtilizationRow struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	AvailableSeats int64  `json:"available_seats"`
	OccupiedSeats  int64  `json:"occupied_seats"`
	SocketSeats    int64  `json:"socket_seats"`
}

// 自习室实时使用统计（含插座统计）
func (q *Queries) GetRoomUtilization(ctx context.Context) ([]GetRoomUtilizationRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomUtilization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoomUtilizationRow{}
	for rows.Next() {
		var i GetRoomUtilizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvailableSeats,
			&i.OccupiedSeats,
			&i.SocketSeats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBehaviorStats = `-- name: GetUserBehaviorStats :one
SELECT 
    u.id,
    COUNT(r.id) FILTER (WHERE r.status = 'completed') as completed_count,
    COUNT(v.id) as violation_count,
    MAX(r.end_time) as last_reservation_time
FROM "user" u
LEFT JOIN reservation r ON u.id = r.user_id
LEFT JOIN violation v ON u.id = v.user_id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserBehaviorStatsRow struct {
	ID                  int32       `json:"id"`
	CompletedCount      int64       `json:"completed_count"`
	ViolationCount      int64       `json:"violation_count"`
	LastReservationTime interface{} `json:"last_reservation_time"`
}

// 用户行为分析（含预约和违约统计）
func (q *Queries) GetUserBehaviorStats(ctx context.Context, id int32) (GetUserBehaviorStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBehaviorStats, id)
	var i GetUserBehaviorStatsRow
	err := row.Scan(
		&i.ID,
		&i.CompletedCount,
		&i.ViolationCount,
		&i.LastReservationTime,
	)
	return i, err
}
