// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: violaton.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createViolationWithCheck = `-- name: CreateViolationWithCheck :one
INSERT INTO violation (user_id, reservation_id, reason)
SELECT $1, $2, $3
FROM reservation 
WHERE id = $2
AND user_id = $1
RETURNING id, user_id, reservation_id, reason, created_at
`

type CreateViolationWithCheckParams struct {
	UserID        int32     `json:"user_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
	Reason        string    `json:"reason"`
}

// 创建关联预约的违约记录
func (q *Queries) CreateViolationWithCheck(ctx context.Context, arg CreateViolationWithCheckParams) (Violation, error) {
	row := q.db.QueryRowContext(ctx, createViolationWithCheck, arg.UserID, arg.ReservationID, arg.Reason)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReservationID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listUserViolation = `-- name: ListUserViolation :many
SELECT v.id, v.user_id, v.reservation_id, v.reason, v.created_at, r.start_time, r.end_time, s.number as seat_number
FROM violation v
JOIN reservation r ON v.reservation_id = r.id
JOIN seat s ON r.seat_id = s.id
WHERE v.user_id = $1
ORDER BY v.created_at DESC
`

type ListUserViolationRow struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
	Reason        string    `json:"reason"`
	CreatedAt     time.Time `json:"created_at"`
	StartTime     time.Time `json:"start_time"`
	EndTime       time.Time `json:"end_time"`
	SeatNumber    string    `json:"seat_number"`
}

// 获取用户违约详情（含预约信息）
func (q *Queries) ListUserViolation(ctx context.Context, userID int32) ([]ListUserViolationRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserViolation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserViolationRow{}
	for rows.Next() {
		var i ListUserViolationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReservationID,
			&i.Reason,
			&i.CreatedAt,
			&i.StartTime,
			&i.EndTime,
			&i.SeatNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
