// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: violaton.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createViolationWithCheck = `-- name: CreateViolationWithCheck :one
INSERT INTO violation (user_id, reservation_id, reason)
SELECT $1, $2, $3
FROM reservation 
WHERE id = $2
AND user_id = $1
RETURNING id, user_id, reservation_id, reason, created_at
`

type CreateViolationWithCheckParams struct {
	UserID        int32     `json:"user_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
	Reason        string    `json:"reason"`
}

// 创建关联预约的违约记录
func (q *Queries) CreateViolationWithCheck(ctx context.Context, arg CreateViolationWithCheckParams) (Violation, error) {
	row := q.db.QueryRowContext(ctx, createViolationWithCheck, arg.UserID, arg.ReservationID, arg.Reason)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReservationID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteViolation = `-- name: DeleteViolation :one
UPDATE violation SET
    reason = COALESCE($2, reason)
WHERE id = $1
RETURNING id, user_id, reservation_id, reason, created_at
`

type DeleteViolationParams struct {
	ID     int32          `json:"id"`
	Reason sql.NullString `json:"reason"`
}

// 更新违约记录
func (q *Queries) DeleteViolation(ctx context.Context, arg DeleteViolationParams) (Violation, error) {
	row := q.db.QueryRowContext(ctx, deleteViolation, arg.ID, arg.Reason)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReservationID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listViolation = `-- name: ListViolation :many
SELECT v.id, v.user_id, v.reservation_id, v.reason, v.created_at FROM violation v
WHERE
    ($3::UUID IS NULL OR v.reservation_id = $3) AND
    ($4::INT IS NULL OR v.user_id = $4)
ORDER BY v.created_at DESC
LIMIT $1 OFFSET $2
`

type ListViolationParams struct {
	Limit         int32         `json:"limit"`
	Offset        int32         `json:"offset"`
	ReservationID uuid.NullUUID `json:"reservation_id"`
	UserID        sql.NullInt32 `json:"user_id"`
}

// 动态查询，可能参数reservation_id, user_id
func (q *Queries) ListViolation(ctx context.Context, arg ListViolationParams) ([]Violation, error) {
	rows, err := q.db.QueryContext(ctx, listViolation,
		arg.Limit,
		arg.Offset,
		arg.ReservationID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Violation{}
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReservationID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
