// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: violaton.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createViolation = `-- name: CreateViolation :one
INSERT INTO violation (user_id, reservation_id)
VALUES ($1, $2)
RETURNING id, user_id, reservation_id, reason, status, created_at
`

type CreateViolationParams struct {
	UserID        int32     `json:"user_id"`
	ReservationID uuid.UUID `json:"reservation_id"`
}

// 创建关联预约的违约记录
func (q *Queries) CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error) {
	row := q.db.QueryRowContext(ctx, createViolation, arg.UserID, arg.ReservationID)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReservationID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getViolation = `-- name: GetViolation :one
SELECT id, user_id, reservation_id, reason, status, created_at FROM violation 
WHERE id = $1
`

// 获取违约记录
func (q *Queries) GetViolation(ctx context.Context, id int32) (Violation, error) {
	row := q.db.QueryRowContext(ctx, getViolation, id)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReservationID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listViolation = `-- name: ListViolation :many
SELECT v.id, v.user_id, v.reservation_id, v.reason, v.status, v.created_at FROM violation v
WHERE
    ($3::UUID IS NULL OR v.reservation_id = $3) AND
    ($4::INT IS NULL OR v.user_id = $4)
ORDER BY v.created_at DESC
LIMIT $1 OFFSET $2
`

type ListViolationParams struct {
	Limit         int32         `json:"limit"`
	Offset        int32         `json:"offset"`
	ReservationID uuid.NullUUID `json:"reservation_id"`
	UserID        sql.NullInt32 `json:"user_id"`
}

// 动态查询，可能参数reservation_id, user_id
func (q *Queries) ListViolation(ctx context.Context, arg ListViolationParams) ([]Violation, error) {
	rows, err := q.db.QueryContext(ctx, listViolation,
		arg.Limit,
		arg.Offset,
		arg.ReservationID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Violation{}
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReservationID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateViolation = `-- name: UpdateViolation :one
UPDATE violation SET
    reason = $2
WHERE id = $1
RETURNING id, user_id, reservation_id, reason, status, created_at
`

type UpdateViolationParams struct {
	ID     int32  `json:"id"`
	Reason string `json:"reason"`
}

// 更新违约记录
func (q *Queries) UpdateViolation(ctx context.Context, arg UpdateViolationParams) (Violation, error) {
	row := q.db.QueryRowContext(ctx, updateViolation, arg.ID, arg.Reason)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReservationID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
